### PR TITLE
fix injectors for sourcemapped code

### PR DESCRIPTION
**Pull request by heilage-nsk**
We should add DI annotations before any sourcemaps. or annotations will be considered as a part of sourcemap and will be cut in downstream.
Pretty ugly hack, but should not break anything.

### CODE REVIEW

**Comment by heilage-nsk** [comment]
@fobos @ovvost

**Comment by fobos** [comment]
Need to discuss tomorrow morning

**Comment by fobos** [comment]
:+1:

**Comment by ovvost** [comment]
:+1:

**Comment by lastw** [comment]
million dollar idea: make uglify to keep components' variables not mangled with regex (`mangle-regex` option in uglify2)

**Comment by heilage-nsk** [comment]
worth trying.

**Comment by heilage-nsk** [comment]
I've played around with mangle-regex for a while and didn't find the way to disable mangling of function argument names. Gonna merge current solution.

**Pull request merged**
